- name: Installing Fish Shell | apt
  apt:
    name: fish
    state: present

- name: Check if Fish is already setup
  register: fish_local
  stat:
    path: "~/.config/fish"

- name: Create fish folder in ~/.config file
  when: not fish_local.stat.exists
  file:
    path: ~/.config/fish
    state: directory

- name: Link ~/config.fish
  when: not fish_local.stat.exists
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/ansible/playbooks/roles/fish/files/config.fish"
    dest: ~/.config/fish/config.fish
    state: link

- name: Sets Fish as default shell | command
  user:
    name: conrad
    shell: /usr/bin/fish

- name: Check if oh-my-fish is installed
  stat:
    path: "/etc/omf.installed"
  register: omf

- name: Clone oh-my-fish repo
  git:
    repo: "https://github.com/oh-my-fish/oh-my-fish"
    dest: "/tmp/omf"
    clone: yes
  when: not omf.stat.exists

- name: Install oh-my-fish
  become: true
  command: fish -c "/tmp/omf/bin/install"
  when: not omf.stat.exists

- name: Install oh-my-fish
  become: true
  command: fish -c "omf install pure"
  when: not omf.stat.exists

- name: Mark oh-my-fish installed with /etc/omf.installed
  when: not omf.stat.exists
  file:
    path: /etc/omf.installed
    state: touch
