- name: Installs zsh | apt
  become: yes
  apt:
    name: zsh
    state: present

- name: Installs curl | apt
  become: yes
  apt:
    name: curl
    state: present

- name: Check if .zshrc exists
  register: file_zshrc
  stat:
    path: ~/.zshrc

- name: Check if .oh-my-zsh exists
  register: repo_oh_my_zsh_dir
  stat:
    path: ~/.oh-my-zsh

- name: Cloning oh-my-zsh
  when: not repo_oh_my_zsh_dir.stat.exists
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh

- name: Link ~/.zshrc
  when: not file_zshrc.stat.exists
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/ansible/playbooks/roles/zsh/files/.zshrc"
    dest: ~/.zshrc
    state: link

- name: Sets zsh as default shell | command
  become: yes
  user:
    name: awake
    shell: /usr/bin/zsh
