- name: Remove zsh | apt
  become: yes
  apt:
    name: zsh
    state: absent

- name: Check if .zshrc exists
  register: file_zshrc
  stat:
    path: ~/.zshrc

- name: Check if .oh-my-zsh exists
  register: repo_oh_my_zsh_dir
  stat:
    path: ~/.oh-my-zsh

- name: Removing cloned oh-my-zsh
  when: repo_oh_my_zsh_dir.stat.exists
  file:
    path: ~/.oh-my-zsh
    state: absent

- name: Remove linked ~/.zshrc
  when: file_zshrc.stat.exists
  file:
    path: ~/.zshrc
    state: absent

- name: Sets Bash as default shell | command
  become: yes
  user:
    name: awake
    shell: /usr/bin/bash
