- name: Set up local (ubuntu) workstation
  hosts: local
  roles:
    - role: packages
    - role: fish
    - role: tmux
    - role: nvim
    - role: docker
    - role: kubernetes
    - role: migibert.terraform
    - role: fubarhouse.golang
