- name: Set up local (ubuntu) workstation
  hosts: local
  roles:
    - role: zsh
      tags:
        - zsh
    - role: fish
      tags:
        - fish
    - role: tmux
      tags:
        - tmux
    - role: nvim
      tags:
        - nvim
