- name: Installing Tmux | api
  apt:
    name: tmux
    state: present

- name: Link ~/.tmux.conf
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/ansible/playbooks/roles/tmux/files/.tmux.conf"
    dest: ~/.tmux.conf
    state: link
