name: Dotfiles Docker
on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Pull docker image
        run: docker-compose pull

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: koenverburg/dotfiles/ubuntu-dotfiles
          registry: docker.pkg.github.com
          build-args: docker-compose up --build --exit-code-from ubuntu-dotfiles
