name: Custom WSL Distro Pipeline

on:
  workflow_dispatch:

jobs:
  Helios:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: run Helios detached
        run: |
          docker run -d --name helios-runner ghcr.io/koenverburg/dotfiles/helios
          docker export --output=helios-wsl-install.tar helios-runner

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ github.token }}
          automatic_release_tag: latest
          prerelease: false
          title: "Custom Ubuntu WSL Distro"
          files: |
            helios-wsl-install.tar
